### ISSUE TITLE
rDHS regions

### ISSUE THREAD

**Issue by cbravo93** [weng-lab/ENCODE-cCREs#1]
Hi!

Thanks for this fantastic resource! I am interested on the unfiltered rDHSs (based on the paper numbers, 2,217,404 and 1,229,135 for hg38 and mm10, respectively). I have found two files in this repository which correspond to rDHSs (ENCODE-cCREs/Version-2/cCRE-Pipeline/Input-Data/hg38/rDHS.hg19-hg38.bed.gz and ENCODE-cCREs/Version-2/cCRE-Pipeline/Input-Data/mm10/rDHS.mm10.bed.gz); however the number of regions does not match exactly (2,114,497 and 1,036,226 regions for hg38 and mm10, respectively). Are these files correct or there is a more recent version? If the latter, would it be possible to share it? I have also checked on ENCODE, but only found cCREs.

Thanks!

C

**Comment by Jill-Moore** [comment]
Dear cbravo:

Thank you for you interest in our work. Yes those files are a previous version used in the current pipeline to manage IDs. I apologize for the the confusion and have renamed them with "V1" in the title to avoid future mixups.

We currently have the filtered lists of rDHSs are available on the ENCODE portal.
hg38: https://www.encodeproject.org/annotations/ENCSR169HLH/
mm10: https://www.encodeproject.org/annotations/ENCSR672RVL/

I have also added a new folder called "[Annotations](https://github.com/weng-lab/ENCODE-cCREs/tree/master/Version-2/cCRE-Pipeline/Annotations)" which has the final and unfiltered versions of rDHSs and cCREs. Please note that the unfiltered version of rDHSs do not have accessions since they are not the final processed version.

Please let me know if you have any additional questions.

Many thanks,
-JEM

**Comment by cbravo93** [comment]
Great, that was exactly what I was looking for! Thanks a ton!
